#!/usr/bin/env python3
"""Render eight pinned O*NET 31.0 linkage tables as provenance-bearing Turtle."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

TABLES = {
    "abilities_to_work_activities": (381, "relevantWorkActivity", "sourceOnet310AbilitiesToWorkActivities"),
    "abilities_to_work_context": (139, "relevantWorkContext", "sourceOnet310AbilitiesToWorkContext"),
    "essential_skills_to_work_activities": (110, "relevantWorkActivity", "sourceOnet310EssentialSkillsToWorkActivities"),
    "essential_skills_to_work_context": (39, "relevantWorkContext", "sourceOnet310EssentialSkillsToWorkContext"),
    "transferable_skills_to_work_activities": (122, "relevantWorkActivity", "sourceOnet310TransferableSkillsToWorkActivities"),
    "transferable_skills_to_work_context": (57, "relevantWorkContext", "sourceOnet310TransferableSkillsToWorkContext"),
    "work_styles_to_work_activities": (303, "relevantWorkActivity", "sourceOnet310WorkStylesToWorkActivities"),
    "work_styles_to_work_context": (266, "relevantWorkContext", "sourceOnet310WorkStylesToWorkContext"),
}

DOMAIN_ROOTS = {
    "abilities": "1.A",
    "essential_skills": "2.A",
    "transferable_skills": "2.B",
    "work_styles": "1.D",
    "work_activities": "4.A",
    "work_context": "4.C",
}


def _term(element_id: str) -> str:
    return "onet31_" + element_id.replace(".", "_")


def _statement(table_id: str, source_id: str, target_id: str) -> str:
    return "onet31Linkage_" + "_".join(
        value.replace(".", "_") for value in (table_id, source_id, target_id)
    )


def render(content_model: Path, sources: tuple[Path, ...]) -> str:
    """Render exact published pairs after endpoint and source-contract validation."""
    content_payload = json.loads(content_model.read_text(encoding="utf-8"))
    content = {row["element_id"]: row["element_name"] for row in content_payload["row"]}
    if len(content) != 3006:
        raise ValueError("content model must contain 3,006 unique elements")
    by_table = {}
    for source in sources:
        payload = json.loads(source.read_text(encoding="utf-8"))
        table_id = payload.get("table_id")
        if table_id not in TABLES or table_id in by_table:
            raise ValueError(f"unexpected or duplicate linkage table {table_id!r}")
        by_table[table_id] = (payload, source)
    if set(by_table) != set(TABLES):
        raise ValueError("all eight O*NET linkage tables are required")

    output = [
        "@prefix : <https://contextualwisdomlab.github.io/LineageWeave/ontology#> .",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "@prefix prov: <http://www.w3.org/ns/prov#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "",
        "# Generated by scripts/render_onet_31_content_model_linkages.py; do not edit by hand.",
    ]
    direct_links = set()
    for table_id, (expected_count, predicate, source_entity) in TABLES.items():
        payload, source_path = by_table[table_id]
        rows = payload.get("row")
        if not isinstance(rows, list) or len(rows) != expected_count:
            raise ValueError(f"{table_id} must contain {expected_count} rows")
        source_url = f"https://www.onetcenter.org/dl_files/database/db_31_0_json/{table_id}.json"
        digest = hashlib.sha256(source_path.read_bytes()).hexdigest()
        output.extend(
            [
                "",
                f":{source_entity} a prov:Entity ;",
                f"    dcterms:title {json.dumps(payload['title'], ensure_ascii=False)}@en ;",
                '    dcterms:publisher "National Center for O*NET Development"@en ;',
                '    dcterms:hasVersion "31.0" ;',
                f"    dcterms:source <{source_url}> ;",
                "    dcterms:license <https://creativecommons.org/licenses/by/4.0/> ;",
                f'    :sourceArtifactSha256 "{digest}" .',
            ]
        )
        source_prefix, target_prefix = table_id.split("_to_")
        pairs = set()
        for row in rows:
            source_id = row[f"{source_prefix}_element_id"]
            target_id = row[f"{target_prefix}_element_id"]
            if not source_id.startswith(f"{DOMAIN_ROOTS[source_prefix]}."):
                raise ValueError(f"{table_id} source endpoint has wrong domain: {source_id}")
            if not target_id.startswith(f"{DOMAIN_ROOTS[target_prefix]}."):
                raise ValueError(f"{table_id} target endpoint has wrong domain: {target_id}")
            if row[f"{source_prefix}_element_name"] != content.get(source_id):
                raise ValueError(f"{table_id} source endpoint mismatch for {source_id}")
            if row[f"{target_prefix}_element_name"] != content.get(target_id):
                raise ValueError(f"{table_id} target endpoint mismatch for {target_id}")
            pair = (source_id, target_id)
            if pair in pairs:
                raise ValueError(f"duplicate pair in {table_id}: {pair}")
            pairs.add(pair)
        for source_id, target_id in sorted(pairs):
            direct = (source_id, predicate, target_id)
            if direct in direct_links:
                raise ValueError(f"duplicate direct linkage across tables: {direct}")
            direct_links.add(direct)
            statement = _statement(table_id, source_id, target_id)
            output.extend(
                [
                    "",
                    f":{_term(source_id)} :{predicate} :{_term(target_id)} .",
                    "",
                    f":{statement} a rdf:Statement, prov:Entity, :OnetContentModelLinkage ;",
                    f"    rdf:subject :{_term(source_id)} ;",
                    f"    rdf:predicate :{predicate} ;",
                    f"    rdf:object :{_term(target_id)} ;",
                    f"    prov:wasDerivedFrom :{source_entity} .",
                ]
            )
    if len(direct_links) != 1417:
        raise ValueError("O*NET 31.0 linkage set must contain 1,417 unique pairs")
    return "\n".join(output) + "\n"


def main() -> int:
    """Render the complete pinned source set without partial output."""
    parser = argparse.ArgumentParser()
    parser.add_argument("content_model", type=Path)
    parser.add_argument("sources", nargs=8, type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render(args.content_model, tuple(args.sources)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
