#!/usr/bin/env python3
"""Render the version-pinned 2018 SOC hierarchy CSV as deterministic Turtle."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

LEVEL_CLASS = {
    "major_group": "OccupationalMajorGroup",
    "minor_group": "OccupationalMinorGroup",
    "broad_occupation": "BroadOccupation",
    "detailed_occupation": "DetailedOccupation",
}


def term_name(code: str) -> str:
    """Return the stable canonical local name for one published SOC code."""
    return f"soc2018_{code.replace('-', '_')}"


def render(source: Path) -> str:
    """Render validated source rows without inferring any absent hierarchy."""
    rows = list(csv.DictReader(source.read_text(encoding="utf-8").splitlines()))
    codes = {row["soc_code"] for row in rows}
    if len(rows) != 1447 or len(codes) != 1447:
        raise ValueError("2018 SOC source must contain 1,447 unique classifications")
    output = [
        "@prefix : <https://contextualwisdomlab.github.io/LineageWeave/ontology#> .",
        "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
        "",
        "# Generated by scripts/render_soc_2018_hierarchy.py; do not edit by hand.",
    ]
    counts = {level: 0 for level in LEVEL_CLASS}
    for row in rows:
        code = row["soc_code"]
        level = row["classification_level"]
        parent = row["broader_soc_code"]
        if level not in LEVEL_CLASS:
            raise ValueError(f"unsupported SOC classification level {level!r}")
        if (level == "major_group") != (not parent):
            raise ValueError(f"invalid broader code for {code}")
        if parent and parent not in codes:
            raise ValueError(f"unknown broader SOC code {parent!r} for {code}")
        counts[level] += 1
        label = json.dumps(row["preferred_title"], ensure_ascii=False)
        statements = [
            f"a skos:Concept, :{LEVEL_CLASS[level]}",
            "skos:inScheme :soc2018Scheme",
            f"skos:prefLabel {label}@en",
            f":socCode {json.dumps(code)}",
        ]
        if parent:
            statements.append(f"skos:broader :{term_name(parent)}")
        output.extend(
            [
                "",
                f":{term_name(code)} " + " ;\n    ".join(statements) + " .",
            ]
        )
    if counts != {
        "major_group": 23,
        "minor_group": 98,
        "broad_occupation": 459,
        "detailed_occupation": 867,
    }:
        raise ValueError(f"unexpected 2018 SOC level counts: {counts}")
    return "\n".join(output) + "\n"


def main() -> int:
    """Render the requested CSV to a file, failing before partial output."""
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    rendered = render(args.source)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
