#!/usr/bin/env python3
"""Render O*NET 31.0 Content Model Reference JSON as deterministic Turtle."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT_CLASS = {
    "1": "WorkerCharacteristicsElement",
    "2": "WorkerRequirementsElement",
    "3": "ExperienceRequirementsElement",
    "4": "OccupationalRequirementsElement",
    "5": "OccupationSpecificInformationElement",
    "6": "WorkforceCharacteristicsElement",
}
BRANCH_CLASS = {
    "1.A": "AbilityElement",
    "1.B": "CareerInterestElement",
    "1.D": "WorkStyleElement",
    "2.A": "EssentialSkillElement",
    "2.B": "TransferableSkillElement",
    "2.C": "KnowledgeElement",
    "2.D": "EducationElement",
    "2.E": "SoftwareSkillElement",
    "3.A": "ExperienceTrainingElement",
    "3.D": "LicensingElement",
    "4.A": "WorkActivityElement",
    "4.C": "WorkContextElement",
    "5.A": "TaskElement",
    "5.C": "OccupationTitleElement",
    "5.D": "OccupationDescriptionElement",
    "5.E": "JobTitleElement",
    "6.A": "LaborMarketInformationElement",
    "6.B": "OccupationalOutlookElement",
}


def term_name(element_id: str) -> str:
    """Return the stable canonical local name for one O*NET element ID."""
    return "onet31_" + element_id.replace(".", "_")


def render(source: Path) -> str:
    """Render exact source IDs, labels, descriptions, and documented parents."""
    payload = json.loads(source.read_text(encoding="utf-8"))
    if payload.get("table_id") != "content_model_reference":
        raise ValueError("source is not O*NET Content Model Reference JSON")
    rows = payload.get("row")
    if not isinstance(rows, list) or len(rows) != 3006:
        raise ValueError("O*NET 31.0 content model must contain 3,006 rows")
    by_id = {row["element_id"]: row for row in rows}
    if len(by_id) != len(rows):
        raise ValueError("O*NET content model contains duplicate element IDs")

    output = [
        "@prefix : <https://contextualwisdomlab.github.io/LineageWeave/ontology#> .",
        "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
        "",
        "# Generated by scripts/render_onet_31_content_model.py; do not edit by hand.",
    ]
    for element_id in sorted(by_id, key=lambda value: tuple(value.split("."))):
        row = by_id[element_id]
        parent = element_id.rsplit(".", 1)[0] if "." in element_id else None
        if parent is not None and parent not in by_id:
            raise ValueError(f"O*NET element {element_id} has unknown parent {parent}")
        root = element_id.split(".", 1)[0]
        if root not in ROOT_CLASS:
            raise ValueError(f"O*NET element {element_id} has unknown root")
        branch = ".".join(element_id.split(".")[:2])
        classes = ["OnetContentModelElement", ROOT_CLASS[root]]
        if branch in BRANCH_CLASS:
            classes.append(BRANCH_CLASS[branch])
        statements = [
            "a skos:Concept, " + ", ".join(f":{name}" for name in classes),
            "skos:inScheme :onet31ContentModelScheme",
            f"skos:prefLabel {json.dumps(row['element_name'], ensure_ascii=False)}@en",
            f"skos:definition {json.dumps(row['description'], ensure_ascii=False)}@en",
            f":onetElementId {json.dumps(element_id)}",
        ]
        if parent is not None:
            statements.append(f"skos:broader :{term_name(parent)}")
        output.extend(
            [
                "",
                f":{term_name(element_id)} " + " ;\n    ".join(statements) + " .",
            ]
        )
    return "\n".join(output) + "\n"


def main() -> int:
    """Render one pinned JSON source to a file after full validation."""
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    rendered = render(args.source)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
